# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Rent.destroy_all
Listing.destroy_all
User.destroy_all
Rating.destroy_all

user_1 = User.create(name: "Rei", password:'rei', image: 'https://nypdecider.files.wordpress.com/2019/04/one-punch-man-1-1.jpg?quality=90&strip=all&w=646&h=431&crop=1')

user_2 = User.create(name:"Pete", password:'pete', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1ZjORmWJA8hWeXd33zV8_azVcV2SsbS16ua6s26hzdiobsf64GA')

user_3 = User.create(name:"Luka", password:'luka', image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtQybnb8Zjijep3qNFkHLyB9cX2JPQ3Ph4_GLQMZwa7zLFEu3JWA")

user_4 = User.create(name:"Mallory",password:'mallory', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROpkNcBKW0I2bTVqdp4DjTW3HrRYbHzeK4j9JaTxKmerr4EgJK')

user_5 = User.create(name:"Ernie",password:'ernie', image:"https://image.shutterstock.com/image-photo/knight-sword-shield-260nw-762608260.jpg")

user_6 = User.create(name:"Dragon",password:'dragon', image:"http://www.howarddavidjohnson.com/Misty_Mountain_Dragon.jpg")

user_7 = User.create(name:"Jamil", password:'gangster', image:"https://thenypost.files.wordpress.com/2018/08/trump_capone.jpg?quality=90&strip=all&w=618&h=410&crop=1")

user_8 = User.create(name:"Susan", password:'susan', image:'https://a-z-animals.com/media/animals/images/470x370/giraffe_10.jpg')



listing_1 = Listing.create(user_id: user_1.id, renter: user_2.id, category:"keyboards", rented: true, image:'https://d2wclktjr2mmlu.cloudfront.net/media/catalog/product/cache/image/680x505/e9c3970ab036de70892d86c6d221abfe/N/o/Nord_Stage3-HP_01.jpg', instrument_name: 'Nord Stage Piano', description: '88-note Triple Sensor key bed with grand weighted action for authentic Piano touch and feel; Nord Virtual Hammer Action Technology enables you to produce a new note without lifting the key completely for smoother repetitions', user_notes: 'Plays really well. The board is in tip top condition, and I rarely play it. It can be a bit heavy to carry so make sure you have a car or transportaion to help with the move.', price: 55)

listing_2 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://www.zeobrothers.com/wp-content/uploads/2017/03/suitcase88.jpg', instrument_name: 'Fender Rhodes', description: 'Mk1 88 key Rhodes suitcase. (piano and large floor standing 4x12 speaker cabinet) The Rhodes Suitcase models all have a 4×12″ cabinet with two speakers facing both directions resulting in a very unique sound when the stereo tremolo circuitry is activated. In addition to this classic tremolo sound, the built in amplification is a huge bonus for players that do not have a competent amplifier to pair with their Rhodes.  This suitcase model is hard to come by! ', user_notes: 'This model is amazing. I honestly cant recommend this keyboard enough. Perfect sound, wonderful tremolo. Would be great for a one-time gig or a recording session.', price: 80)

listing_3 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://hammondorgans.com.au/wp-content/uploads/2017/03/2Hammond-Organ-B-3-Mark-2-New-Release-large-1.jpg', instrument_name: 'B3 Hammond Organ', description: '1957
HAMMOND B-3 with Bass Pedals, PR40 & JR10 (Rare) Tone Cabinets, Bench, with all the original cables.', user_notes: 'Organ and all cabinets have been Church kept, is in excellent working condition.There are some minor bumps and scratches consistent with the age. Local Pickup or other arrangements can be made. Ask any questions you need.', price: 120)

listing_4 = Listing.create(user_id: user_3.id, category: "guitars", renter: user_4.id, rented: true, image:'https://americanvintageguitar.com/wp-content/uploads/2017/02/60-strat_9205-800.jpg', instrument_name: '1960 American Fender Stratocaster', description: 'Fender started the 60s strong introducing new models like the Jaguar and the Jazz Bass. The Stratocaster of 1960 changed little from the Strat of 1959. By this point almost all Strats have the slab Rosewood fingerboard, as well as the updated 3-ply pickguard. The neck continued to be made in a thin D-shaped profile.', user_notes: 'Ive owned the Guitar since 1997, and its never left my House. Slab Board w Clay Dots. 8.9 Condition, aside from the chemical reaction on the back from the original Cord, and a few minor nicks. This is a definite Investment Grade Guitar.  Un-circulated, Second Owner Guitar.', price: 110)

listing_5 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--fGdI9AE4--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1531500177/ws98amsh1lcnaad0qubp.jpg', instrument_name: 'Gibson Les Paul Custom 1978 Cherry Sunburst', description: 'While made during one of the companys most controversial eras when many players saw a sacrifice of quality for profit margins, the Gibson Les Paul Customs of the Norlin Era can be diamond-in-the-rough finds for players with a keen eye. In particular, if youre looking for iconic LP growl with the workhorse construction that made these guitars a legend in the first place, many guitarists and luthiers alike point to the late 70s/early 80s models as capstones of the era.', user_notes: 'Fantastic 1978 custom Les Paul. Is absolutely incredible sounding that only comes with 40 years of age and wood maturation. Frets are in great shape and it’s a dream to play. Light scratches on the back of guitar and patina on the pickups. Has OHSC (chainsaw case) with the Gibson branding. ', price: 50)

listing_6 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--ibrhZfoX--/f_auto,t_supersize/v1537376748/logc2nqbudxpohccpbe2.jpg', instrument_name: 'Gretsch Round Badge Drum Set', description: '14x18 Bass Drum, 8x12 Rack Toms, 14x14 Floor Tom, 5x14 Snare Drum, 7 Ply Maple, 30 Degree Bearing Edge, Gretsch Double Flanged “302” Hoops,Gretsch Silver Sealer,UPC: 647139387444', user_notes: 'The 2016 Renown delivers the traditional Gretsch sound with an incredible open, harmonic tone that supplies the versatility needed to meet the demands of the hardest working drummers.', price: 45)

listing_7 = Listing.create(user_id: user_4.id, category: "drums", renter: user_5.id, rented: true, image:'https://images.reverb.com/image/upload/s--_Gfjvg14--/f_auto,t_supersize/v1562008674/jh2z7gclcfwe2gfznqtx.jpg', instrument_name: 'Ludwig Classic Maple Ringo Star 3 Piece Drum Set Kit', description: 'Rack Tom-9x13, Floor Tom-16x16, Bass Drum-14x22', user_notes: 'This is kit is in mint condition, with minimal stick marks on the batter heads, and no blemishes in the cosmetic view of the shells. The floor tom comes with the Atlas floor tom brackets, and the rack tom comes with no mounting bracket.', price: 80)

listing_8 = Listing.create(user_id: user_4.id, category: "drums", renter: user_5.id, rented: true, image:'https://images.reverb.com/image/upload/s--nRt5l5si--/f_auto,t_large/v1562016195/hhdjopgut1gsqu79ugzl.jpg', instrument_name: 'Pearl Session Studio 3pc Drum Kit MINT', description: 'This item is in excellent working condition, barely used, and includes original packaging.', user_notes: 'This item is in excellent working condition, barely used, and includes original packaging.',price: 65)

listing_9 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--j5-HCWal--/f_auto,t_large/v1562012666/xwmuggchzkfnn6500k86.jpg', instrument_name: 'DW Maple Collector 2003', description: 'Sizes are diameter by depth. All drums have factory re-rings and gold hardware! 22x18, 16x13, 14x12, 12x9, 10x8', user_notes: 'These drums sound as great as they look. They are head turners in every way. It’s a 2003 Exotic Quilted Maple over standard maple shells. The color is Amber to tobacco burst. Condition is really good',price: 90)

listing_10 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--yGZTJXBr--/f_auto,t_supersize/v1551809094/qmf7ztzzq4yswinyazns.jpg', instrument_name: 'Fender Jazz Bass Sunburst 1962', description: 'One piece maple neck with unbound Brazilian rosewood slab board. 7MAR62A neck stamp. Original black bobbin pickups and wiring with 1962 pot codes. The bridge pickup has been rewound. Neck 7.9k ohms bridge 7.1k ohms.Original hardware except for replaced neck pickup cover.', user_notes: 'The fingerboard has been removed and reglued, probably in order to repair the truss rod. The side dots were replaced during this process. -The guitar has been refretted. The fingerboard was planed for the the refret and is somewhat thin towards the neck heel. -The nut has been replaced. -The neck pickup cover is not original. -The bridge pickup has been rewound.', price: 90)

listing_11 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--WZ-33-re--/f_auto,t_supersize/v1554329703/cd2ypkwnz9kdnjw6op2q.jpg', instrument_name: 'Fender Precision Bass 1962', description: 'Refinished Body.Alder Body.Alder Solid Body -- The body has been refinished.Maple Neck.Fingerboard Material: Brazilian Rosewood.Neck Profile: D-Shape.Neck Thickness (IN): 1st fret: .82" / 12th: .98". Fingerboard Radius: 7.25. Nut Width: 1-11/16 in', user_notes: 'Currently, set up with 50-105 gauge strings and low action. The truss rod is all the way loose - We recommend this bass setup with at least medium gauge strings for optimal relief and truss rod adjustability. -- The serial number and pot codes date to 1962.', price: 45)

listing_12 = Listing.create(user_id: user_2.id, category: "basses", renter: user_6.id, rented: true, image:'https://images.reverb.com/image/upload/s--wcxIs7mp--/f_auto,t_large/v1524070874/bgwdartjly44wfw5wah7.jpg', instrument_name: '2017 Rickenbacker', description: 'The Rickenbacker 4003 Bass in Natural Maple Glow! Rickenbacker 4003 Bass Maple Glo Natural With Case The Classic Rickenbacker bass - famous for its ringing sustain, treble punch and solid underlying bass. A subtle strip of binding graces the elegantly curved body and the Rosewood fingerboard.', user_notes: '2017 Rickenbacker 4003 Mapleglo Bass in Brand New Condition. Comes with original hard shell case.', price: 48)

listing_13 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--TSbs_hOR--/f_auto,t_supersize/v1537914296/oqlgb2uxm3vxcexdwuww.jpg', instrument_name: 'Fender Player Jaguar Bass', description: 'The Rickenbacker 4003 Bass in Natural Maple Glow! Rickenbacker 4003 Bass Maple Glo Natural With Case The Classic Rickenbacker bass - famous for its ringing sustain, treble punch and solid underlying bass. A subtle strip of binding graces the elegantly curved body and the Rosewood fingerboard.', user_notes: '2017 Rickenbacker 4003 Mapleglo Bass in Brand New Condition. Comes with original hard shell case.', price: 48)


listing_14 = Listing.create(user_id: user_8.id, category: "brass", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--4FpBij7X--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1532534164/wgazkdccwzhrf7xfdlny.jpg', instrument_name: 'Bach Stradivarious Series Bb Trumpet', description: 'The #25 leadpipe allows for slight resistance that is effective in centering tone production. These features combined with a .459-inch medium-large bore allow the player to produce a well-rounded sound while not over-extending the endurance level of the player.', user_notes: 'Good for all-around playing, this Bach 180 Strad Pro Trumpet features a standard weight body and #37 bell, plus a standard construction #25 mouthpipe in silver finish. The most popular Bach Stradivarius trumpet available today is the 180S37 with a yellow brass bell. ', price: 34)

listing_15 = Listing.create(user_id: user_8.id, category: "brass", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--oBb3n6hR--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1487353822/k2r5jfzbqtqdvranxa6b.jpg', instrument_name: 'Bach Model 42B Stradivarius Tenor Trombone', description: 'Stradivarius Bb/F, .547" bore, 8-1/2" one-piece hand-hammered yellow brass bell, chrome plated nickel-silver inner handslide tubes, brass outer handslide tubes, traditional wrap "F" section with traditional rotor, clear lacquer finish, genuine Vincent Bach 6-1/2A large shank mouthpiece and zippered Cordura covered wood shell case.', user_notes: 'Beautiful sounding trombone. Ive playing this trombone for years and have always really enjoyed playing it. ', price: 60)

listing_16 = Listing.create(user_id: user_8.id, category: "brass", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--nOviLmzU--/f_auto,t_supersize/v1561661772/uhkoswosz0lvs4firmyd.jpg', instrument_name: 'EM Winston Baritone', description: 'Allora 500 Series instruments, like this AEP-550 Paris Series Compensating Euphonium, provide professional quality. ', user_notes: 'They are perfect for advancing students, adult enthusiasts and professional musicians.This item was returned in great condition. It looks and plays like new, with only minor signs of use (slight scuffs, etc.).', price: 25)

listing_17 = Listing.create(user_id: user_8.id, category: "brass", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--81_OXwro--/f_auto,t_supersize/v1562002805/ri5gptaqcvkitcoprhk1.jpg', instrument_name: 'Yamaha Standard Bb Cornet', description: 'Cornets are highly recommended for beginner band students, instead of a trumpet. These are easier to handle and cheaper, compared to the longer, heavier, and harder to play trumpet.', user_notes: 'Perfect condition Yamaha cornet! We purchased it from Mississippi Music in Jackson, MS in 2016. It was only used for 2 years and cleaned quite often. The cornet, mouthpiece, and trumpet/cornet cleaning kit (valve oil, tuning slide grease, cleaning tools) are included PLUS extra slightly-used valve oil and tuning slide grease. ', price: 25)

listing_18 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--9iDAcdOn--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1529356288/alxzmhqhlussanmediil.jpg', instrument_name: 'Fender Player Series Telecaster', description: 'Fenders all new Player Telecaster is here to help you take your next step forward in your guitar playing journey. Featuring authentic Fender tone, a great set of pickups, and enhanced playability, this guitar is a professional level solidbody with a full lifetime of playing ahead of it. The entire line up of new Player Series models are some of the finest guitars Fender has made at a price that is incredibly affordable.', user_notes: 'This guitar is in perfect condition. It plays great and sounds great. Just had it reset and had some new stings put on it as well!', price: 46)

listing_19 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--3HQbtr82--/f_auto,t_supersize/v1562691030/b6jlxmdfxt5l4yjneo3x.jpg', instrument_name: 'Gibson Les Paul Custom 1990am White', description: 'Great example of Gibson’s famous Les Paul Custom. 100% original except pickups were swapped for Bare Knuckles. Originals are included though. No breaks or repairs. Clean guitar that was pampered', user_notes: 'Great example of Gibson’s famous Les Paul Custom. 100% original except pickups were swapped for Bare Knuckles. Originals are included though. No breaks or repairs. Clean guitar that was pampered', price: 46)

listing_20 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--QwmMMnbw--/f_auto,t_supersize/v1545857403/bcfjvnvspy7j3bynjiki.jpg', instrument_name: 'Gibson USA SG Standard Olive Drab', description: 'Like the greatest SGs ever made, the SG Standard starts with a foundation of solid mahogany, a tonewood with a long tradition at Gibson. A solid mahogany body is crafted in the distinctive, thin asymmetrical dual-cutaway style, with iconic pointed “horns” and beveled edges to enhance playing comfort. A solid, Grade-A, quarter-sawn mahogany neck is glued into the body in Gibson’s time-tested tradition, and carved to a fast, slim taper profile.', user_notes: 'This is still by far one of my all time favorite guitars. Eveytime I need that really really nice growl I always use this bad boy. Comes with a travel case! ', price: 53)

listing_21 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--MGW-5Lw5--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_620,q_90,w_620/v1487277553/zoantuzuense7vfyaoig.jpg', instrument_name: 'Martin D-28 Dreadnought Acoustic Guitar', description: 'Sometimes innovation is in the details and this is certainly true with Martin’s re-imagined D-28. After nearly a century at the helm, and as the quintessential workhorse of music legends like Hank Williams, The Beatles, Johnny Cash, Neil Young, Bob Dylan, and so many more, Martins legendary D28 has been lovingly and artfully enhanced. “The post WWII D-28 had a slightly different look than its predecessor and became the centerpiece of the folk and folk rock movements at their pinnacle in the 1950s and 1960s." says Chris Martin, Chairman and CEO of Martin Guitar, "We have extracted the finest features from the D-28 of both my grandfather’s and my father’s respective eras.”', user_notes: 'Great guitar.Brand new and ready to play! Used only once at a recording session and recorded amazingly.', price: 33)

listing_22 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--vntfeW6i--/f_auto,t_supersize/v1525380679/kan4xpjbww89pxuefusw.jpg', instrument_name: 'Martin Backpacker Traveling Acoustic Guitar with Bag', description: 'Tech Specs String Type Steel Number of Strings 6 Body Shape Backpacker, 15-fret Body Style Other Left-/Right-handed Right-handed Color Natural Finish Matte Top Wood Solid Spruce Back & Sides Wood Solid Tonewoods Body Bracing Backpacker Neck Wood Select Hardwood Fingerboard Material Select Hardwood Fingerboard Inlay Dots (5th and 12th fret only) Neck Shape Backpacker Number of Frets 15 Scale Length 24" Tuning Machines Chrome with Small Knobs Bridge Material Select Hardwood Nut/Saddle Material Corian/Micarta Nut Width 1.6875 Strings Martin M170 Extra-Light 80/20 Bronze Case Included Gig Bag
', user_notes: 'Just because youre leaving home doesnt mean you need to give up guitar playing - the Backpacker can go anywhere you go. The Backpacker is perfectly shaped and constructed for portability and travel, yet it still provides the best in tone and feel. Features steel strings. Comes with Padded Carrying Bag.', price: 33)

listing_23 = Listing.create(user_id: user_3.id, category: "guitars", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--o5Myoxpf--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1513130749/udakbhu9weedzvxgby92.jpg', instrument_name: 'Taylor 414CE Grand Auditorium 2002 Model', description: 'A beautiful Grand Auditorium acoustic guitar of the 414 series by Taylor. Brand new old stock, from the former Taylor European distribution, hand-selected example, previously kept for the Taylor history collection for guitar exhibitions and similar purposes, in perfect collectors condition!', user_notes: 'Due to the fact that this guitar is professionally stored by the distributor, the woods were able to age longer & perfectly to emphasize its rich sound characteristics. A very rare opportunity to receive a guitar of this time in such a marvelous condition!', price: 33)

listing_24 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--Zp9PB-cZ--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1487002146/goqqgcknfvbr1dfb5nbu.jpg', instrument_name: 'Korg micro 37-Key Synthesizer and Vocoder', description: 'The Korg MICROKORG is a lightweight, portable synthesizer and MIDI controller keyboard, with 37 velocity sensitive miniature keys, serving the DJ and Techno markets. The small but intense footprint of the keyboard and the provision for AA battery power, contribute to this keyboards usefulness as a mobile, laptop composing and production tool. The LED illuminated selection buttons and display make live performance, in dark venues, significantly easier.', user_notes: 'This little guy packs a mean punch. It has the capability to play and tamper with so so many sounds.The pitch and modulation wheels, along with the 5 parameter control knobs, are real-time controllers, a welcome stage or studio performance feature.', price: 30)

listing_25 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--dACtYH9I--/f_auto,t_supersize/v1562633512/wxueht2sf3pfag1hi5wu.jpg', instrument_name: 'KORG 770 Vintage Analog Synthesizer', description: 'An ancient synthesizer from Korg. Aside from being very old, there isnt much else to say about the 770. It was released in 1976, is monophonic, very limited in design, flexibility and sonic possibility. It can make some weird noises largely due to its retro-cool ring modulator. You can also run external sounds through it. Bass, string and lead sounds are ok. Its got a fast envelope, auto bend, and LFO re-trigger too. An ole classic thats fun to play with and useful if youre in the mood for buzzy analog sounds.', user_notes: 'In excellent condition. There are some minor scratches and cosmetic wear and very minor damages to the wood part but overall in excellent physical condition. All functions are working well, all keys and sliders are functions without any problems. ', price: 73)

listing_26 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--_Qxf6a5B--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1523496431/fhwgrewbad2vh7tkseb7.jpg', instrument_name: 'MiniMoog Model D, Late 1970s Vintage Analog Synthesizer', description: 'MiniMoog Model D, Serial No. 12864, circa 1979. Excellent working condition with re-foamed road case with rollers. Recently serviced by Custom Vintage Keyboards in Burbank, CA: new key bushings, buss bars cleaned refitted and adjusted, potentiometers cleaned and calibrated. A few minor dings in wood casing, see photos. Has that classic patented Moog 24db per octave ladder bridge filter sound that is so often emulated, but never duplicated, even by the new Model D reissues. ', user_notes: 'This synth is in excellent condition and sounds incredible. If youre looking for some super vibed out sounds this is for you. I will not lease for long trips or tours. ', price: 84)

listing_27 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--d-yN-jlf--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1501233276/bfqtsdpgoeastkb7hyry.jpg', instrument_name: 'Farfisa Farfisa String Orchestra', description: 'Vintage Italian Transistor String Synthesizer freshly serviced. MADE IN ITALY,aprox. 1975,super rare, weight around 40kg´s, comes with original stand, comes with volume pedal, comes with sustain pedal.Fully serviced, awesome sound!', user_notes: 'This is a really weird instrument hahaha. It definitely sounds like that late 60s sounding, Beach Boys album shit. You will love it if thats what youre going for.', price: 69)

listing_28 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--UZ5V6iY0--/f_auto,t_supersize/v1562642426/ezwswqrtvok0e2q3hdj9.jpg', instrument_name: 'Ibanez ATK300 2007 Natural', description: 'The ATK is big–with the big, bold tones you get from a traditional big neck and big body. But the ATK is no one-trick trad workhorse. Its also versatile and comfortable thanks to its unique electronics and physical layout. In other words, the right choice for blues, hard rock, country players and anyone else who wants every single plus of a traditional bass and more.', user_notes: 'This bass has a huge sound. Great for country and rock gigs. Ive toured with it many many times and its been a tried and true bass over the years. Leasing for tours and long travel so please let me know if youd like to!', price: 48)

listing_29 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--HXTC5Mpk--/f_auto,t_supersize/v1561575029/a3fdaka9azqvdjmgmawn.jpg', instrument_name: 'Schecter Michael Anthony Signature Bass', description: 'Schecter Michael Anthony Electric Bass Best known for his comprehensive and influential work with Van Halen, Michael Anthony (currently playing with Chickenfoot and The Circle) has rocked the bass for nearly fifty years, showcasing his skill, sound, and style in venues of all sizes across the globe. Modified from their well-known Model T line to better suit Anthonys preferences, the Michael Anthony Bass has a solid alder body and a slightly slimmer maple/walnut multi-ply neck for fast action up and down the instrument. Exciting Schecter USA MonsterTone P/J pickups bring powerful, focused lows and the WSC bridge and tuners give you incredible stability. The deep cobalt grey finish and creme binding accent the look and put the finishing touches on this incredible bass drawn from one of the most well-known bassists in rock.', user_notes: 'This bass has ALOT of bass if you know what I mean. It has a really really full sound that is super stable and steady. Ive been blessed to have this in my arsenal for so long and now im happy to share this beauty with my fellow low-end brothers and sisters', price: 48)

listing_30 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--rbL9q9WO--/f_auto,t_large/v1562686862/y6cmtjphpocszoq2l8tk.jpg', instrument_name: 'Ernie Ball Music Man StingRay SR5 HH 2019 Vintage Sunburst', description: 'Ernie Ball Sting Ray 5 HH Sunburst, Roasted Maple Neck and,Fretboard,Chrome Hardware,White Pickguard,22 Stainless Steel Frets,5 Bolt Sculpted Heal Joint,Neo Pick Up Magnets,18 Volt Pre-Amp,Light Weight Aluminum Hardware,
Case Included', user_notes: 'This 5 string badass bass is all the bass youll need for a fusion gig or wedding. Cant say I use it all that often cause Im more of a 4 string dude myself, but for those of you out there that cant fit all those basslines in without going lower then this one is for you. Please dont play chords on this cause that is just dumb.', price: 48)

listing_31 = Listing.create(user_id: user_2.id, category: "basses", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--0_4k-7Fh--/f_auto,t_supersize/v1541696999/xzqu6emuxhi0bsia2gki.jpg', instrument_name: '2002 Hofner 500/2 Club Bass', description: 'The current Hofner Club Bass H500/2 is a vintage reissue of the original 500/2 model bass from the 1960s. It features a hollow body with a short 30" scale length. Not to be confused with the Limited Edition model that has much closer spaced humbuckers, or with the cheaper Ignition model with Staple pickups.', user_notes: 'If it werent for the label within, everyone would think this bass is a vintage mid-60s original. However, with better, more refined,craftsmanship, and a closer attention to detail, this bass will out-perform the majority of vintage examples. No case.
Unusual finish checking on the neck.', price: 42)

listing_32 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--x7IIzigB--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1486575111/u9w3germwe6clqcgrjzh.jpg', instrument_name: 'Gretsch Catalina Club Classic 4 Piece Kit', description: 'The Gretsch Catalina Club Classic is a four-piece drum set for the active player who needs great sound out of a kit that sets up and tears down quickly and easily. Featuring mahogany shells with 30-degree bearing edges and a natural interior, this set projects a warm, punchy, classic tone.The 20 x 14" bass drum is easy to handle and has a full-bodied voice with plenty of punch. When combined with the 12-inch tom and 14-inch floor tom, the resulting combination is a drum set with outstanding tone-ready to tackle anything from jazz to fusion, to blues, to rock.', user_notes: 'This kit is incredible. Whether youre a beginner or a seasoned player youll love the sound of this kit. Please let me know if this is a rental that will be taken on tour or not',price: 63)

listing_33 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--Q5b4rj1q--/f_auto,t_supersize/v1562696165/zqx2u1xaspu83zj2ujji.jpg', instrument_name: 'Gretsch 3-Piece Broadkaster Drumset Vintage', description: 'Super clean single owner Gretsch 3-Piece Broadkaster in Vintage Champagne sizes 12/14/20. 3-Ply North American maple/poplar shells with Silver Sealer, rounded over bearing edges with Gretsch 302 hoops.', user_notes: 'This vintage kit is in really really good condition. For the time being Im only renting it out for recording sessions. If youre looking for a vintage sound this is the go to kit.',price: 82)

listing_34 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--TlQZ4_Q5--/f_auto,t_supersize/v1562272200/gsegm9gszxy2dgbn0g9c.jpg', instrument_name: '1964 Rogers Swingtime Outfit Vintage Drum Kit', description: '14x20 : The bass drum is in great condition with original Blue Sparkle wrap, strong seams, and original flat grey interior. The hoops retain their original black paint and each have a full set of inlay, free from any cracks or issues. The bearing edges are factory sharp and the hardware has very strong chrome. One of the collets has a very slightly loose ear but nothing that affects playability or setup. 8x12: The 8x12 tom is also in great condition with all original hardware, beautiful Blue Sparkle wrap and factory original interior.', user_notes: 'Aside from a few very minor scratches, this kit is perfect collector condition and player! Nothing quite sounds as great as these early 60s Rogers drums. Only allowing this rental for recording sessions.',price: 100)

listing_35 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--vYxTZJ6E--/f_auto,t_supersize/v1562343314/jdgotgrbmih2qgntjoup.jpg', instrument_name: 'Rogers Holiday 1968 Jet Black Bop Kit', description: 'These are Rogers drums from 1968. The model is Holiday and the specific outfit as configured and cataloged would be the Citadel with the optional 14x18 bass drum. The floor tom is 14x14 and mounted tom is 8x12. The tom arm, bass drum spurs and and the floor tom legs are included, so it is a complete three-piece set-up to which youll need to add your snare drum, hardware and cymbals. It also includes the factory-installed Sta-tite mount on the side of the floor tom with a straight rod and Swivomatic wood block mounting device. This is a rather unique extra that was presumably special-ordered like the bass drum. ', user_notes: 'The floor tom legs are the correct 21" version, but are reproductions from JP-2 Creations. Unfortunately, I misplaced the original ones in a move from MA to ME. Also note that the screws securing lugs in the bass drum have round head slotted screws, whereas the toms have hex-head slotted screws. Please message me if you plan to use this kit for one-off shows or tours.',price: 78)

listing_36 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--b5LuBDcK--/f_auto,t_supersize/v1548282084/jnwrk73oqgbctf2e1twf.jpg', instrument_name: 'Ludwig 110th Anniversary Legacy Mahogany', description: 'This anniversary outfit hallmarks some of Ludwig’s most coveted drums that date back to the 1930s. Flash Pearl Inlay made its debut as a high-end finishing feature to further personalize and amplify the presentation of your drum set. Utilizing dyed Tupelo and Koto veneers, precision-cut diamond figures are inlaid into arctic white birds-eye maple veneer. This presentation is made complete with Ludwig’s revered Legacy Mahogany 3-ply shell design. Limited to 20 units worldwide as a Fab Configuration: 14x22 bass drum, 16x16 floor tom, 9x13 tom tom and matching snare drum (sold separately). Each outfit features Ludwig’s 110th Anniversary embossed badge.', user_notes: 'This is a remake kit. Its in fantastic condition and sounds amazing. If youre looking for a kit with a versitle sound this kit is perfect for all types of sounds. Try it out!',price: 144)

listing_37 = Listing.create(user_id: user_4.id, category: "drums", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--HF9IwNTL--/c_crop,h_0.563,w_1.000,x_0.000,y_0.155/f_auto,t_supersize/v1529608394/k4paepuqazbfgibqppev.jpg', instrument_name: 'Ludwig club dates 1963 silver', description: '67 Ludwig spurs and mounts on the kick, and rogers floor tom legs and mounts on the floor tom ,this set sounds great. 20 inch kick  12 tom and 14 floor tom ,great for jazz or rock ,you cant beat the sound of vintage drums. This is just the three drums and lets and tom mounts no cymbals.', user_notes: 'The kit is all intact and ready to roll. I usually dont allow this oldie to travel around so I prefer only studio sessions.',price: 50)

listing_38 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--LRzhioA6--/c_crop,h_1.000,w_0.563,x_0.187,y_0.000/f_auto,t_supersize/v1561494723/ilrigroq5ui7syqg4fut.jpg', instrument_name: 'Yamaha B1 Polished Ebony Upright Piano ', description: 'Full Length ribs into a notched liner.Laminated soundboard.Acoustibars.Solid cooper wound bass strings.Hard Beech bridges.Aluminum alloy action rails.Yamaha balanced action. Spruce Keys with Hardwood buttons.Grand Piano Key Travel.Cut thread tuning pins.Yamaha designed hammers with T-Fastners.Mute Pedal.Vacuum Shield Mold Process (V-Pro) plate.Seasoned for Destination.Comes with matching bench', user_notes: 'Are you looking for a great deal on an Yamaha Piano.  Well you have found it.  This B1pec 43 vertical inch upright was just traded in for a grand piano.  Regularly tuned to A-440 this instrument was kept in pristine condition.  Hurry up deals like this don’t come by often.',price: 133)

listing_39 = Listing.create(user_id: user_1.id, category: "keyboards", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--NpsMlsA4--/f_auto,t_supersize/v1546917242/axpbej009w3akndpy4j0.jpg', instrument_name: 'Straco 43 Key Golden Piano 1950s', description: 'It has 25 white keys and 18 black keys - total of 43 keys. Measures 26" Tall, 26" Wide and 25" Deep.', user_notes: 'Up for grabs is this cool 50s vintage Imperial Straco Grand Piano, as pictured.  This is a steel rod chime type of toy piano. This is the biggest toy piano of this type Ive ever seen.  If youre a fan of Pockets and his legendary Kazookeylele, this could be the ideal candidate for a double-bass version!
',price: 12)

listing_40 = Listing.create(user_id: user_8.id, category: "brass", renter: nil, rented: false, image:'https://images.reverb.com/image/upload/s--a5uqFNQF--/f_auto,t_supersize/v1562479962/fwoobrowaal9yrg07byq.jpg', instrument_name: 'Yamaha Standard Bb Cornet', description: '', user_notes: 'Tuba has a small dent on my main tuning slide, purely cosmetic and does not change playing at all. Comes with hard case with minor scratches', price: 25)







rating_1 = Rating.create(rater_id: user_2.id, rated_id: user_1.id, stars: 5, review: "Rei was great. I rented his Fender Rhodes for a recording session I had and it was a dream to play. Thanks again Rei will rent again soon!")

rating_2 = Rating.create(rater_id: user_2.id, rated_id: user_3.id, stars: 4, review: "Luka was great owner. I rented his Fender Strat for a tour I had on the East Coast and it was very successful! Luka youre the man!")

rating_3 = Rating.create(rater_id: user_4, rated_id: user_1.id, stars: 3, review: "Rei was a great guy, the only reason Im giving a 3 for this was cause there was a big miscommunication on his part and I wasnt able to borrow his Nord Keyboard for the time we agreed on. Make sure you double check your dates in the future...")

rating_4 = Rating.create(rater_id: user_3.id, rated_id: user_1.id, stars: 4, review: "Rei was a good guy. I plan on renting from him again soon.")

rating_5 = Rating.create(rater_id: user_4.id, rated_id: user_1.id, stars: 4, review: "LOVE the Nord. I can't say it enough I HAVE to get one of these ASAP. Thanks for letting me borrow yours Rei.")

rating_6 = Rating.create(rater_id: user_1.id, rated_id: user_3.id, stars: 4, review: "Luka was crying when I showed up. THOSE TEARS!!! Get ready for Friday LUKA!")
